In [4]:
import torch
import torch.nn as nn
import numpy as np
a = data = np.random.rand(10, 2)
b =  np.moveaxis(a, 0, -1)
b = b[:,:,np.newaxis]
print(a)
print(b)





[[0.60005962 0.43332733]
 [0.02026937 0.83627956]
 [0.15971269 0.99979323]
 [0.05944601 0.24699404]
 [0.84683011 0.88299519]
 [0.30052512 0.35818583]
 [0.88465216 0.14566447]
 [0.59910327 0.60145355]
 [0.21735502 0.72638485]
 [0.28741221 0.4233679 ]]
[[[0.60005962]
  [0.02026937]
  [0.15971269]
  [0.05944601]
  [0.84683011]
  [0.30052512]
  [0.88465216]
  [0.59910327]
  [0.21735502]
  [0.28741221]]

 [[0.43332733]
  [0.83627956]
  [0.99979323]
  [0.24699404]
  [0.88299519]
  [0.35818583]
  [0.14566447]
  [0.60145355]
  [0.72638485]
  [0.4233679 ]]]


In [7]:
import  torch
data = torch.randn(2,10,1)
x_p = data.permute(1, 0, 2)
x_p_new = x_p.squeeze()
print(data)
print(x_p)
print(x_p_new)




tensor([[[-1.0082],
         [-0.6055],
         [ 0.1351],
         [-0.9193],
         [-0.9924],
         [-0.6731],
         [-1.5681],
         [ 0.3806],
         [-0.7775],
         [-0.2772]],

        [[-0.2303],
         [ 0.7309],
         [ 2.1551],
         [-1.6122],
         [-1.1881],
         [-0.2781],
         [-0.8394],
         [ 2.4978],
         [-0.4216],
         [ 1.0201]]])
tensor([[[-1.0082],
         [-0.2303]],

        [[-0.6055],
         [ 0.7309]],

        [[ 0.1351],
         [ 2.1551]],

        [[-0.9193],
         [-1.6122]],

        [[-0.9924],
         [-1.1881]],

        [[-0.6731],
         [-0.2781]],

        [[-1.5681],
         [-0.8394]],

        [[ 0.3806],
         [ 2.4978]],

        [[-0.7775],
         [-0.4216]],

        [[-0.2772],
         [ 1.0201]]])
tensor([[-1.0082, -0.2303],
        [-0.6055,  0.7309],
        [ 0.1351,  2.1551],
        [-0.9193, -1.6122],
        [-0.9924, -1.1881],
        [-0.6731, -0.2781],
        

In [3]:
import torch
size = 3

m = (torch.tril(torch.ones(size, size)) == 1)
print(m)
d =  m.transpose(0, 1)
print(d)

tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True,  True]])
tensor([[ True,  True,  True],
        [False,  True,  True],
        [False, False,  True]])


In [46]:
import pandas as pd
import json
import re

data = """9|2023-06-29 15:23:11.323842|{"晶升": null, "主加功率": null, "晶转": null, "埚转": null, "直径": null, "设定生长速度": null, "实际生长速度": null, "液口距": null, "实际液面温度": null, "埚升": null, "晶体长度": null, "晶体重量": null, "状态": null, "底加功率": null, "温度速率": null, "功率速率": null, "埚跟比": null, "主室压力": null, "干泵频率/节流阀开度": null, "氩气流量": null, "坩埚位置": null, "籽晶位置": null, "热屏位置": null, "净重": null, "总重量": null, "提出重量": null, "剩余重量": null, "放肩角度": null, "热屏水温": null, "热屏流量": null, "PRESSURE_PC": null, "主加电流": null, "直径原始": null}|{"晶升指令": 68.27431522380324}

9|2023-06-29 15:23:11.763151|{"晶升": null, "主加功率": null, "晶转": null, "埚转": null, "直径": null, "设定生长速度": null, "实际生长速度": null, "液口距": null, "实际液面温度": null, "埚升": null, "晶体长度": null, "晶体重量": null, "状态": null, "底加功率": null, "温度速率": null, "功率速率": null, "埚跟比": null, "主室压力": null, "干泵频率/节流阀开度": null, "氩气流量": null, "坩埚位置": null, "籽晶位置": null, "热屏位置": null, "净重": null, "总重量": null, "提出重量": null, "剩余重量": null, "放肩角度": null, "热屏水温": null, "热屏流量": null, "PRESSURE_PC": null, "主加电流": null, "直径原始": null}|{"晶升指令": 69.54103721295611}"""

# 解析整个字符串
# datas = data.split('|2023-06-29')
# for s in datas:
#     if "晶升" in s:
#         print(s)
#         print("...")
datas = re.split("2023-06-29", data)
print(datas)
df_data = pd.DataFrame()
for s in datas:
    if "晶升" in s:
        s_in =    [x for x in s.split("|") if x]
        # print(s)
        # print("s_in:",s_in)
        # print("s_in[0]:",s_in[0])
        # print("s_in[1]:",s_in[1])
        # print("s_in[2]:",s_in[2].split("}")[0]+"}")


        data_dict = json.loads(s_in[1])
        json_time = {"时间": s_in[0]}
        json_append =  json.loads(s_in[2].split("}")[0]+"}")
        # print(data_dict)
        # print(type(data_dict))
        # print(type(json_time))
        # print(type(json_append))
        dict_concat = {**json_time,**json_append,**data_dict }
        # print(dict_concat)
        # 转换为DataFrame
        df_one = pd.DataFrame(dict_concat, index=[0])
        df_data=pd.concat([df_data,df_one],axis=0,ignore_index=True)

df_data.to_csv("all_data.csv")


['9|', ' 15:23:11.323842|{"晶升": null, "主加功率": null, "晶转": null, "埚转": null, "直径": null, "设定生长速度": null, "实际生长速度": null, "液口距": null, "实际液面温度": null, "埚升": null, "晶体长度": null, "晶体重量": null, "状态": null, "底加功率": null, "温度速率": null, "功率速率": null, "埚跟比": null, "主室压力": null, "干泵频率/节流阀开度": null, "氩气流量": null, "坩埚位置": null, "籽晶位置": null, "热屏位置": null, "净重": null, "总重量": null, "提出重量": null, "剩余重量": null, "放肩角度": null, "热屏水温": null, "热屏流量": null, "PRESSURE_PC": null, "主加电流": null, "直径原始": null}|{"晶升指令": 68.27431522380324}\n\n9|', ' 15:23:11.763151|{"晶升": null, "主加功率": null, "晶转": null, "埚转": null, "直径": null, "设定生长速度": null, "实际生长速度": null, "液口距": null, "实际液面温度": null, "埚升": null, "晶体长度": null, "晶体重量": null, "状态": null, "底加功率": null, "温度速率": null, "功率速率": null, "埚跟比": null, "主室压力": null, "干泵频率/节流阀开度": null, "氩气流量": null, "坩埚位置": null, "籽晶位置": null, "热屏位置": null, "净重": null, "总重量": null, "提出重量": null, "剩余重量": null, "放肩角度": null, "热屏水温": null, "热屏流量": null, "PRESSURE_PC": null, "主加电流": null, "直径原始