In [4]:
import torch
import torch.nn as nn
import numpy as np
a = data = np.random.rand(10, 2)
b =  np.moveaxis(a, 0, -1)
b = b[:,:,np.newaxis]
print(a)
print(b)





[[0.60005962 0.43332733]
 [0.02026937 0.83627956]
 [0.15971269 0.99979323]
 [0.05944601 0.24699404]
 [0.84683011 0.88299519]
 [0.30052512 0.35818583]
 [0.88465216 0.14566447]
 [0.59910327 0.60145355]
 [0.21735502 0.72638485]
 [0.28741221 0.4233679 ]]
[[[0.60005962]
  [0.02026937]
  [0.15971269]
  [0.05944601]
  [0.84683011]
  [0.30052512]
  [0.88465216]
  [0.59910327]
  [0.21735502]
  [0.28741221]]

 [[0.43332733]
  [0.83627956]
  [0.99979323]
  [0.24699404]
  [0.88299519]
  [0.35818583]
  [0.14566447]
  [0.60145355]
  [0.72638485]
  [0.4233679 ]]]


In [7]:
import  torch
data = torch.randn(2,10,1)
x_p = data.permute(1, 0, 2)
x_p_new = x_p.squeeze()
print(data)
print(x_p)
print(x_p_new)




tensor([[[-1.0082],
         [-0.6055],
         [ 0.1351],
         [-0.9193],
         [-0.9924],
         [-0.6731],
         [-1.5681],
         [ 0.3806],
         [-0.7775],
         [-0.2772]],

        [[-0.2303],
         [ 0.7309],
         [ 2.1551],
         [-1.6122],
         [-1.1881],
         [-0.2781],
         [-0.8394],
         [ 2.4978],
         [-0.4216],
         [ 1.0201]]])
tensor([[[-1.0082],
         [-0.2303]],

        [[-0.6055],
         [ 0.7309]],

        [[ 0.1351],
         [ 2.1551]],

        [[-0.9193],
         [-1.6122]],

        [[-0.9924],
         [-1.1881]],

        [[-0.6731],
         [-0.2781]],

        [[-1.5681],
         [-0.8394]],

        [[ 0.3806],
         [ 2.4978]],

        [[-0.7775],
         [-0.4216]],

        [[-0.2772],
         [ 1.0201]]])
tensor([[-1.0082, -0.2303],
        [-0.6055,  0.7309],
        [ 0.1351,  2.1551],
        [-0.9193, -1.6122],
        [-0.9924, -1.1881],
        [-0.6731, -0.2781],
        